name: Docker Image CI

on:
  pull_request:
    branches: [ master ]

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: Build and push base image
        uses: docker/build-push-action@v2
        with:
          context: ./base
          push: false
          tags: hadoop-hive-spark-base:latest

      - name: Build and push master image
        uses: docker/build-push-action@v2
        with:
          context: ./master
          push: false
          tags: hadoop-hive-spark-master:latest

      - name: Build and push worker image
        uses: docker/build-push-action@v2
        with:
          context: ./worker
          push: false
          tags: hadoop-hive-spark-worker:latest

      - name: Build and push history image
        uses: docker/build-push-action@v2
        with:
          context: ./history
          push: false
          tags: hadoop-hive-spark-history:latest

      - name: Build and push jupyter image
        uses: docker/build-push-action@v2
        with:
          context: ./jupyter
          push: false
          tags: hadoop-hive-spark-jupyter:latest
