name: Docker Image CI

on:
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: Build and push base image
        uses: docker/build-push-action@v2
        with:
          context: ./base
          push: false
          tags: myamafuj/hadoop-hive-spark-base

      - name: Build and push master image
        uses: docker/build-push-action@v2
        with:
          context: ./master
          push: false
          tags: myamafuj/hadoop-hive-spark-master

      - name: Build and push worker image
        uses: docker/build-push-action@v2
        with:
          context: ./worker
          push: false
          tags: myamafuj/hadoop-hive-spark-worker

      - name: Build and push history image
        uses: docker/build-push-action@v2
        with:
          context: ./history
          push: false
          tags: myamafuj/hadoop-hive-spark-history

      - name: Build and push jupyter image
        uses: docker/build-push-action@v2
        with:
          context: ./jupyter
          push: false
          tags: myamafuj/hadoop-hive-spark-jupyter
