name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: Build the base image
        run: docker build --file ./base/Dockerfile --tag hadoop-hive-spark-base:$(date +%s)

      - name: Build the master image
        run: docker build --file ./master/Dockerfile --tag hadoop-hive-spark-master:$(date +%s)

      - name: Build the worker image
        run: docker build --file ./worker/Dockerfile --tag hadoop-hive-spark-worker:$(date +%s)

      - name: Build the history image
        run: docker build --file ./history/Dockerfile --tag hadoop-hive-spark-history:$(date +%s)

      - name: Build the jupyter image
        run: docker build --file ./jupyter/Dockerfile --tag hadoop-hive-spark-jupyter:$(date +%s)
