name: Docker Image CI

on:
  pull_request:
    branches: [ master ]

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push base image
        uses: docker/build-push-action@v3
        with:
          context: ./base
          push: true
          tags: myamafuj/hadoop-hive-spark-base:latest

      - name: Build and push master image
        uses: docker/build-push-action@v3
        with:
          context: ./master
          push: true
          tags: myamafuj/hadoop-hive-spark-master:latest

      - name: Build and push worker image
        uses: docker/build-push-action@v3
        with:
          context: ./worker
          push: true
          tags: myamafuj/hadoop-hive-spark-worker:latest

      - name: Build and push history image
        uses: docker/build-push-action@v3
        with:
          context: ./history
          push: true
          tags: myamafuj/hadoop-hive-spark-history:latest

      - name: Build and push jupyter image
        uses: docker/build-push-action@v3
        with:
          context: ./jupyter
          push: true
          tags: myamafuj/hadoop-hive-spark-jupyter:latest
